### ISSUE TITLE
Add changelog.md

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/jinja2-git#12]
We are ready for a new release!

@mikhail-akimov but before releasing a new version, we need to add a `CHANGELOG.md` file where  we can describe what have changed since the last version.

What needs to be done:
1. Look at the example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CHANGELOG.md
2. Write about the first version: it was just an initial release
3. Write about your changes: new features and general changes

And then I will release a new version.

**Comment by mikhail-akimov** [comment]
Initioal version was 0.0.1? Current - 0.0.2 or 0.1.0 ?

**Comment by sobolevn** [comment]
`0.2.0`, since we have some new features.

**Comment by mikhail-akimov** [comment]
I cant uderstand why so many diffs between my master (or my last branch) and project.

**Comment by sobolevn** [comment]
The simple way to fix it:
0. backup your work
1. delete your fork
2. fork it again
3. create a new brach for this feature: `issue-12`
4. send a pr

The correct way would also include rebasing master after each merged PR: https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by sobolevn** [comment]
Closed via https://github.com/sobolevn/jinja2-git/pull/14

**Comment by sobolevn** [comment]
I will release a new version shortly.

**Comment by sobolevn** [comment]
@mikhail-akimov can you please write your email address? I need it to add it here: https://github.com/sobolevn/jinja2-git/blob/master/pyproject.toml#L8-L10

**Comment by mikhail-akimov** [comment]
Sure! daggerito@gmail.com

**Comment by sobolevn** [comment]
@mikhail-akimov released! https://github.com/sobolevn/jinja2-git/releases/tag/0.2.0
Thanks to you 🙂

**Comment by mikhail-akimov** [comment]
No problem! Thank you to!
