### ISSUE TITLE
Support `python3.7`

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/jinja2-git#8]
There's a new python version that we currently do not officially support. 

What need to be done:
1. We need to remove these classifiers: https://github.com/sobolevn/jinja2-git/blob/master/pyproject.toml#L30-L34
2. We need to add new python version here: https://github.com/sobolevn/jinja2-git/blob/master/pyproject.toml#L38, example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml#L40
3. We need to add `python3.7` inside travis builds, example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/.travis.yml#L3-L9

**Comment by mikhail-akimov** [comment]
I should to add 3.7 to 3.6 or replace it with?

**Comment by sobolevn** [comment]
We should support both for now.

**Comment by mikhail-akimov** [comment]
Like this "python = "~2.7 || ^3.6 || ^3.7"" ? 
Is the entry with the triple version correct?

**Comment by sobolevn** [comment]
Yeap
